//! Typed memory metadata — structured classification and quality metrics for memory entries.
//!
//! Each memory entry in the evolution system carries a `MemoryMeta` struct that
//! classifies its type, tracks confidence/importance/stability, and records its
//! source and lifecycle status. `MemoryMeta` is serialized into `StoreItem.value`
//! JSON alongside the `content` field, requiring no changes to the `Store` trait
//! or `StoreItem` schema.

use serde::{Deserialize, Serialize};

// ── MemoryType ──────────────────────────────────────────────────────────

/// Classification of a memory entry.
///
/// Every memory must be typed — untyped free-text entries are not allowed
/// in the evolution system. The type determines how the memory is scored,
/// reviewed, and potentially promoted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryType {
    /// A stable user preference (e.g., "user prefers concise answers").
    UserPreference,
    /// A fact about the project (e.g., "this project uses Maven with Java 8").
    ProjectFact,
    /// An architecture or product decision (e.g., "we chose SQLite over Postgres").
    ArchitectureDecision,
    /// A debugging lesson learned (e.g., "Maven compile fails if JAVA_HOME is wrong").
    DebuggingLesson,
    /// An error symptom, cause, and verified solution.
    ErrorResolution,
    /// A commonly used command, environment variable, or build step.
    CommandPattern,
    /// Experience with a specific tool (e.g., "rg is faster than grep for this project").
    ToolUsage,
    /// A repeated workflow pattern that may become a skill candidate.
    WorkflowPattern,
    /// A workflow that has been identified as a potential skill.
    SkillCandidate,
    /// A note that has been superseded or is no longer accurate, kept for traceability.
    DeprecatedNote,
}

impl MemoryType {
    /// Default stability for this memory type (how resistant to becoming stale).
    ///
    /// Higher values mean the memory is less likely to become outdated quickly.
    pub fn default_stability(&self) -> f32 {
        match self {
            Self::UserPreference => 0.85,
            Self::ProjectFact => 0.60,
            Self::ArchitectureDecision => 0.80,
            Self::DebuggingLesson => 0.55,
            Self::ErrorResolution => 0.50,
            Self::CommandPattern => 0.40,
            Self::ToolUsage => 0.50,
            Self::WorkflowPattern => 0.60,
            Self::SkillCandidate => 0.55,
            Self::DeprecatedNote => 0.10,
        }
    }

    /// Whether this memory type is eligible for promotion to a skill.
    pub fn is_skill_eligible(&self) -> bool {
        matches!(
            self,
            Self::WorkflowPattern | Self::SkillCandidate | Self::DebuggingLesson
        )
    }

    /// Whether this memory type is eligible for rule promotion.
    pub fn is_rule_eligible(&self) -> bool {
        matches!(
            self,
            Self::UserPreference | Self::ArchitectureDecision | Self::ProjectFact
        )
    }
}

// ── MemoryRisk ──────────────────────────────────────────────────────────

/// Risk level of a memory entry.
///
/// High-risk memories (from untrusted sources or containing sensitive content)
/// require additional review before promotion to hot memory or rules.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryRisk {
    /// Low risk — can be automatically processed and promoted.
    #[default]
    Low,
    /// Medium risk — may need review before promotion.
    Medium,
    /// High risk — from untrusted source or containing sensitive content.
    /// Must not be promoted to hot memory or rules without human approval.
    High,
}

// ── MemoryProvenance ───────────────────────────────────────────────────

/// Role that supplied one exact excerpt supporting a memory candidate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryEvidenceRole {
    /// Text written by the user.
    User,
    /// Text generated by the assistant.
    Assistant,
    /// Text returned by a tool or another external effect.
    Tool,
}

/// One exact source excerpt supporting a memory candidate.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryEvidence {
    /// Role that supplied the excerpt.
    pub role: MemoryEvidenceRole,
    /// Verbatim excerpt from that role's message.
    pub quote: String,
}

impl MemoryEvidence {
    /// Create evidence from one exact source excerpt.
    pub fn new(role: MemoryEvidenceRole, quote: impl Into<String>) -> Self {
        Self {
            role,
            quote: quote.into(),
        }
    }
}

/// Trust classification derived from evidence roles, not from model output.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryTrust {
    /// All evidence is direct user text.
    User,
    /// All evidence is assistant-generated text.
    Assistant,
    /// All evidence is tool output.
    Tool,
    /// Evidence combines more than one role.
    Mixed,
    /// Historical record written before provenance became mandatory.
    #[default]
    LegacyUnknown,
}

/// Caller-owned approval that may activate one exact Draft snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryApproval {
    /// Stable caller-generated identity used for retry idempotency.
    pub approval_id: String,
    /// Host or reviewer identity that made the decision.
    pub reviewer: String,
    /// Approval timestamp in Unix seconds.
    pub approved_at: u64,
}

impl MemoryApproval {
    /// Create an explicit approval receipt.
    pub fn new(
        approval_id: impl Into<String>,
        reviewer: impl Into<String>,
        approved_at: u64,
    ) -> Self {
        Self {
            approval_id: approval_id.into(),
            reviewer: reviewer.into(),
            approved_at,
        }
    }

    /// Whether this receipt carries the minimum stable identity.
    pub fn is_valid(&self) -> bool {
        !self.approval_id.trim().is_empty() && !self.reviewer.trim().is_empty()
    }
}

/// Durable origin and approval facts for a typed memory.
///
/// A missing field in an older serialized record decodes as legacy unknown
/// with no evidence or approval. Such a record stays inspectable but cannot
/// enter automatic recall.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryProvenance {
    /// Trust derived from the exact evidence roles.
    pub trust: MemoryTrust,
    /// Exact source excerpts used to create the candidate.
    #[serde(default)]
    pub evidence: Vec<MemoryEvidence>,
    /// Explicit caller-owned approval for this exact candidate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval: Option<MemoryApproval>,
}

impl MemoryProvenance {
    /// Create an unapproved provenance record for a Draft candidate.
    pub fn draft(trust: MemoryTrust, evidence: Vec<MemoryEvidence>) -> Self {
        Self {
            trust,
            evidence,
            approval: None,
        }
    }

    /// Whether roles and excerpts substantiate the declared trust.
    pub fn is_well_formed(&self) -> bool {
        if self.evidence.is_empty()
            || self.evidence.iter().any(|evidence| {
                evidence.quote.trim().is_empty()
                    || evidence.quote.chars().take(1_001).count() > 1_000
            })
        {
            return false;
        }
        let has_user = self
            .evidence
            .iter()
            .any(|evidence| evidence.role == MemoryEvidenceRole::User);
        let has_assistant = self
            .evidence
            .iter()
            .any(|evidence| evidence.role == MemoryEvidenceRole::Assistant);
        let has_tool = self
            .evidence
            .iter()
            .any(|evidence| evidence.role == MemoryEvidenceRole::Tool);
        match self.trust {
            MemoryTrust::User => has_user && !has_assistant && !has_tool,
            MemoryTrust::Assistant => has_assistant && !has_user && !has_tool,
            MemoryTrust::Tool => has_tool && !has_user && !has_assistant,
            MemoryTrust::Mixed => {
                [has_user, has_assistant, has_tool]
                    .into_iter()
                    .filter(|present| *present)
                    .count()
                    > 1
            }
            MemoryTrust::LegacyUnknown => false,
        }
    }

    /// Whether this provenance is well formed and explicitly approved.
    pub fn is_approved(&self) -> bool {
        self.is_well_formed() && self.approval.as_ref().is_some_and(MemoryApproval::is_valid)
    }

    /// A preference attributed to the user needs an actual user excerpt.
    pub fn has_user_evidence(&self) -> bool {
        self.evidence
            .iter()
            .any(|evidence| evidence.role == MemoryEvidenceRole::User)
    }
}

// ── MemoryStatus ────────────────────────────────────────────────────────

/// Lifecycle status of a memory entry.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryStatus {
    /// Newly created, not yet confirmed or stabilized.
    Draft,
    /// Confirmed and in active use.
    #[default]
    Active,
    /// Replaced by a newer memory entry. `superseded_by` in `MemoryMeta` points to the replacement.
    Superseded,
    /// Archived — no longer active, kept for traceability.
    Archived,
}

// ── MemorySource ────────────────────────────────────────────────────────

/// How this memory entry was created.
///
/// The source determines the default confidence level and whether the memory
/// can be automatically promoted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemorySource {
    /// Extracted from a user correction signal (e.g., "不要这样做").
    UserCorrection,
    /// Extracted from a tool failure → success sequence.
    ErrorResolution,
    /// Detected from a repeated workflow pattern across sessions.
    RepeatedWorkflow,
    /// Explicitly saved by the user (e.g., `/remember` command).
    ExplicitSave,
    /// Automatically extracted by heuristic or LLM review.
    AutoExtracted,
    /// Promoted from L3 context compression.
    L3Promotion,
}

impl MemorySource {
    /// Default confidence for memories from this source.
    pub fn default_confidence(&self) -> f32 {
        match self {
            Self::ExplicitSave => 1.0,
            Self::UserCorrection => 0.90,
            Self::ErrorResolution => 0.85,
            Self::RepeatedWorkflow => 0.75,
            Self::AutoExtracted => 0.60,
            Self::L3Promotion => 0.50,
        }
    }

    /// (stage4) Default recall weight for memories from this source (0.0–1.0).
    /// Used by composite score for recall ranking.
    pub fn default_recall_weight(&self) -> f32 {
        match self {
            Self::ExplicitSave => 0.8,
            Self::UserCorrection => 0.9,
            Self::ErrorResolution => 0.7,
            Self::RepeatedWorkflow => 0.6,
            Self::AutoExtracted => 0.4,
            Self::L3Promotion => 0.4,
        }
    }
}

// ── MemoryMeta ──────────────────────────────────────────────────────────

/// Structured metadata for a typed memory entry.
///
/// Serialized into `StoreItem.value` JSON as:
/// ```json
/// {
///   "content": "The actual memory text",
///   "meta": { "memory_type": "debugging_lesson", "confidence": 0.85, ... }
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MemoryMeta {
    /// Classification of this memory.
    pub memory_type: MemoryType,
    /// How confident we are that this memory is accurate (0.0–1.0).
    pub confidence: f32,
    /// How stable this memory is — resistance to becoming stale (0.0–1.0).
    pub stability: f32,
    /// (stage4) Recall weight 0.0–1.0, by agent LLM at write time.
    /// Used for composite-score recall ranking (hermes issue #677 calls it "importance").
    /// Named `recall_weight` to avoid colliding with `StoreItem.importance`
    /// (1.0–10.0, prune-resistance, store.rs:29) — same name, different
    /// semantics/scale. Composite score MUST read this field, not StoreItem.importance.
    #[serde(default = "default_recall_weight")]
    pub recall_weight: f32,
    /// Risk level — determines review requirements.
    pub risk: MemoryRisk,
    /// Lifecycle status of this memory.
    pub status: MemoryStatus,
    /// How this memory was created.
    pub source: MemorySource,
    /// Exact origin evidence, trust, and explicit activation receipt.
    #[serde(default)]
    pub provenance: MemoryProvenance,
    /// Topic category (e.g., "build", "debugging", "architecture").
    pub topic: String,
    /// Number of times this memory has been revised.
    #[serde(default)]
    pub revision_count: u32,
    /// (stage4) How many times this memory has been recalled. Drives Dreaming
    /// self-evolution (recall-frequency-driven promotion).
    #[serde(default)]
    pub recall_count: u32,
    /// Last successful recall timestamp (Unix seconds).
    ///
    /// Kept separately from `StoreItem::updated_at`: incrementing recall
    /// telemetry rewrites metadata and would otherwise look like a semantic
    /// content edit to staleness logic.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_recalled_at: Option<u64>,
    /// If this memory was superseded, key of the replacement memory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub superseded_by: Option<String>,
}

/// Serde default for `MemoryMeta::recall_weight` (used when deserializing
/// entries written before the field existed).
fn default_recall_weight() -> f32 {
    0.5
}

impl MemoryMeta {
    /// Create a new MemoryMeta with type and source, using their default values.
    pub fn new(memory_type: MemoryType, source: MemorySource, topic: impl Into<String>) -> Self {
        Self {
            confidence: source.default_confidence(),
            stability: memory_type.default_stability(),
            memory_type,
            recall_weight: source.default_recall_weight(),
            risk: MemoryRisk::default(),
            status: MemoryStatus::default(),
            source,
            provenance: MemoryProvenance::default(),
            topic: topic.into(),
            revision_count: 0,
            recall_count: 0,
            last_recalled_at: None,
            superseded_by: None,
        }
    }

    /// Create a MemoryMeta with explicit confidence.
    pub fn with_confidence(mut self, confidence: f32) -> Self {
        self.confidence = confidence.clamp(0.0, 1.0);
        self
    }

    /// Create a MemoryMeta with explicit stability.
    pub fn with_stability(mut self, stability: f32) -> Self {
        self.stability = stability.clamp(0.0, 1.0);
        self
    }

    /// (stage4) Create a MemoryMeta with explicit recall weight (0.0–1.0).
    pub fn with_recall_weight(mut self, recall_weight: f32) -> Self {
        self.recall_weight = recall_weight.clamp(0.0, 1.0);
        self
    }

    /// Create a MemoryMeta with explicit risk.
    pub fn with_risk(mut self, risk: MemoryRisk) -> Self {
        self.risk = risk;
        self
    }

    /// Create a MemoryMeta with explicit status.
    pub fn with_status(mut self, status: MemoryStatus) -> Self {
        self.status = status;
        self
    }

    /// Create a MemoryMeta with explicit origin evidence.
    pub fn with_provenance(mut self, provenance: MemoryProvenance) -> Self {
        self.provenance = provenance;
        self
    }

    /// Whether this record may enter automatic or tool-driven recall.
    pub fn is_recallable(&self) -> bool {
        matches!(self.status, MemoryStatus::Active | MemoryStatus::Archived)
            && self.provenance.is_approved()
            && self.has_required_evidence()
    }

    /// Whether the evidence supports the meaning of this memory type.
    pub fn has_required_evidence(&self) -> bool {
        self.memory_type != MemoryType::UserPreference || self.provenance.has_user_evidence()
    }

    /// Whether this memory is eligible for promotion to hot memory.
    pub fn is_hot_eligible(&self) -> bool {
        self.confidence >= 0.85
            && self.stability >= 0.70
            && self.status == MemoryStatus::Active
            && self.is_recallable()
            && self.risk != MemoryRisk::High
    }

    /// Whether this memory is eligible for rule promotion.
    pub fn is_rule_eligible(&self) -> bool {
        self.confidence >= 0.95
            && self.stability >= 0.90
            && self.status == MemoryStatus::Active
            && self.is_recallable()
            && self.revision_count == 0
            && self.risk != MemoryRisk::High
            && self.memory_type.is_rule_eligible()
    }

    /// Compute a staleness score (0.0 = fresh, 1.0 = very stale).
    ///
    /// This is a simplified version; the full `StalenessScorer` in Phase 2
    /// incorporates age, usage, and contradiction factors.
    pub fn base_staleness(&self) -> f32 {
        // Low stability → high staleness risk
        let instability = 1.0 - self.stability;
        // Low confidence → higher staleness
        let unconfidence = 1.0 - self.confidence;
        // Deprecated status → high staleness
        let status_factor = match self.status {
            MemoryStatus::Active => 0.0,
            MemoryStatus::Draft => 0.1,
            MemoryStatus::Superseded => 0.8,
            MemoryStatus::Archived => 1.0,
        };

        (instability * 0.35 + unconfidence * 0.25 + status_factor * 0.40).min(1.0)
    }
}

impl Default for MemoryMeta {
    fn default() -> Self {
        Self {
            memory_type: MemoryType::ProjectFact,
            confidence: 0.5,
            stability: 0.5,
            recall_weight: 0.5,
            risk: MemoryRisk::Low,
            status: MemoryStatus::Active,
            source: MemorySource::AutoExtracted,
            provenance: MemoryProvenance::default(),
            topic: String::new(),
            revision_count: 0,
            recall_count: 0,
            last_recalled_at: None,
            superseded_by: None,
        }
    }
}

// ── TypedMemoryValue ────────────────────────────────────────────────────

/// The JSON structure stored in `StoreItem.value` for typed memories.
///
/// This is the serialization format: the `content` field holds the actual
/// memory text, and `meta` holds the structured metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TypedMemoryValue {
    /// The actual memory text content.
    pub content: String,
    /// Structured metadata for this memory.
    pub meta: MemoryMeta,
}

impl TypedMemoryValue {
    /// Create a new typed memory value.
    pub fn new(content: impl Into<String>, meta: MemoryMeta) -> Self {
        Self {
            content: content.into(),
            meta,
        }
    }

    /// Serialize to a `serde_json::Value` for storage in `StoreItem.value`.
    pub fn to_value(&self) -> serde_json::Result<serde_json::Value> {
        serde_json::to_value(self)
    }

    /// Deserialize from a `serde_json::Value`.
    pub fn from_value(value: &serde_json::Value) -> serde_json::Result<Self> {
        serde_json::from_value(value.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_memory_type_default_stability() {
        assert!(
            MemoryType::UserPreference.default_stability()
                > MemoryType::CommandPattern.default_stability()
        );
        assert!(
            MemoryType::ArchitectureDecision.default_stability()
                > MemoryType::ErrorResolution.default_stability()
        );
    }

    #[test]
    fn test_memory_source_default_confidence() {
        assert_eq!(MemorySource::ExplicitSave.default_confidence(), 1.0);
        assert!(
            MemorySource::UserCorrection.default_confidence()
                > MemorySource::AutoExtracted.default_confidence()
        );
    }

    #[test]
    fn test_memory_meta_new() {
        let meta = MemoryMeta::new(
            MemoryType::DebuggingLesson,
            MemorySource::ErrorResolution,
            "build",
        );
        assert_eq!(meta.memory_type, MemoryType::DebuggingLesson);
        assert_eq!(meta.source, MemorySource::ErrorResolution);
        assert_eq!(meta.topic, "build");
        assert_eq!(meta.confidence, 0.85); // ErrorResolution default
        assert_eq!(meta.status, MemoryStatus::Active);
        assert_eq!(meta.risk, MemoryRisk::Low);
    }

    #[test]
    fn test_memory_meta_builder() {
        let meta = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::ExplicitSave,
            "style",
        )
        .with_confidence(0.99)
        .with_stability(0.95)
        .with_risk(MemoryRisk::Medium);
        assert!((meta.confidence - 0.99).abs() < f32::EPSILON);
        assert!((meta.stability - 0.95).abs() < f32::EPSILON);
        assert_eq!(meta.risk, MemoryRisk::Medium);
    }

    #[test]
    fn test_hot_eligible() {
        let provenance = MemoryProvenance {
            trust: MemoryTrust::User,
            evidence: vec![MemoryEvidence::new(
                MemoryEvidenceRole::User,
                "User prefers Rust",
            )],
            approval: Some(MemoryApproval::new("hot-approval", "reviewer", 1)),
        };
        let meta = MemoryMeta::new(MemoryType::ProjectFact, MemorySource::ExplicitSave, "test")
            .with_confidence(0.90)
            .with_stability(0.80)
            .with_provenance(provenance.clone());
        assert!(meta.is_hot_eligible());
        assert!(
            !meta
                .clone()
                .with_provenance(MemoryProvenance::default())
                .is_hot_eligible()
        );

        let low_confidence =
            MemoryMeta::new(MemoryType::ProjectFact, MemorySource::AutoExtracted, "test")
                .with_confidence(0.50)
                .with_provenance(provenance);
        assert!(!low_confidence.is_hot_eligible());
    }

    #[test]
    fn test_rule_eligible() {
        let provenance = MemoryProvenance {
            trust: MemoryTrust::User,
            evidence: vec![MemoryEvidence::new(
                MemoryEvidenceRole::User,
                "User prefers concise answers",
            )],
            approval: Some(MemoryApproval::new("rule-approval", "reviewer", 1)),
        };
        let meta = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::ExplicitSave,
            "style",
        )
        .with_confidence(0.99)
        .with_stability(0.95)
        .with_provenance(provenance.clone());
        assert!(meta.is_rule_eligible());

        // Not eligible: wrong type
        let bug_meta = MemoryMeta::new(
            MemoryType::DebuggingLesson,
            MemorySource::ErrorResolution,
            "test",
        )
        .with_confidence(0.99)
        .with_stability(0.95)
        .with_provenance(provenance.clone());
        assert!(!bug_meta.is_rule_eligible());

        // Not eligible: high risk
        let risky = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::ExplicitSave,
            "test",
        )
        .with_confidence(0.99)
        .with_stability(0.95)
        .with_provenance(provenance)
        .with_risk(MemoryRisk::High);
        assert!(!risky.is_rule_eligible());
    }

    #[test]
    fn test_typed_memory_value_roundtrip() {
        let meta = MemoryMeta::new(
            MemoryType::DebuggingLesson,
            MemorySource::ErrorResolution,
            "build",
        );
        let value = TypedMemoryValue::new("Maven needs Java 8", meta);
        let json = value.to_value().unwrap();
        let parsed = TypedMemoryValue::from_value(&json).unwrap();
        assert_eq!(parsed.content, "Maven needs Java 8");
        assert_eq!(parsed.meta.memory_type, MemoryType::DebuggingLesson);
        assert_eq!(parsed.meta.topic, "build");
    }

    #[test]
    fn test_typed_memory_value_backward_compat() {
        // Old-format store items (no meta field) should be parseable with defaults
        let old_format = serde_json::json!({
            "content": "Some old memory"
        });
        // This should still parse — meta will get serde defaults
        let _parsed: Result<TypedMemoryValue, _> = serde_json::from_value(old_format);
        // If meta is required, this will fail — that's expected.
        // The TypedMemoryStore handles backward compat by catching parse errors.
    }

    #[test]
    fn legacy_metadata_decodes_without_becoming_recallable() -> serde_json::Result<()> {
        let old = serde_json::json!({
            "memory_type": "project_fact",
            "confidence": 0.99,
            "stability": 0.95,
            "risk": "low",
            "status": "active",
            "source": "l3_promotion",
            "topic": "project",
            "revision_count": 0
        });
        let meta: MemoryMeta = serde_json::from_value(old)?;
        assert_eq!(meta.status, MemoryStatus::Active);
        assert_eq!(meta.provenance.trust, MemoryTrust::LegacyUnknown);
        assert!(!meta.is_recallable());
        assert!(!meta.is_hot_eligible());
        Ok(())
    }

    #[test]
    fn provenance_rejects_mismatched_role_empty_and_unbounded_quotes() {
        let mut provenance = MemoryProvenance::draft(
            MemoryTrust::User,
            vec![MemoryEvidence::new(MemoryEvidenceRole::Tool, "tool result")],
        );
        assert!(!provenance.is_well_formed());
        provenance.evidence = vec![MemoryEvidence::new(MemoryEvidenceRole::User, "  ")];
        assert!(!provenance.is_well_formed());
        provenance.evidence = vec![MemoryEvidence::new(
            MemoryEvidenceRole::User,
            "x".repeat(1_001),
        )];
        assert!(!provenance.is_well_formed());
        provenance.evidence = vec![MemoryEvidence::new(
            MemoryEvidenceRole::User,
            "User confirmed this preference",
        )];
        assert!(provenance.is_well_formed());
        assert!(!provenance.is_approved());
        provenance.approval = Some(MemoryApproval::new("approval", "reviewer", 1));
        assert!(provenance.is_approved());
    }

    #[test]
    fn approved_assistant_preference_is_not_recallable() {
        let mut provenance = MemoryProvenance::draft(
            MemoryTrust::Assistant,
            vec![MemoryEvidence::new(
                MemoryEvidenceRole::Assistant,
                "Prefer Rust",
            )],
        );
        provenance.approval = Some(MemoryApproval::new("review", "reviewer", 1));
        let preference = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::AutoExtracted,
            "preference",
        )
        .with_status(MemoryStatus::Active)
        .with_confidence(0.99)
        .with_stability(0.99)
        .with_provenance(provenance);
        assert!(!preference.is_recallable());
        assert!(!preference.is_hot_eligible());
        assert!(!preference.is_rule_eligible());
    }

    #[test]
    fn test_staleness_active_low() {
        let meta = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::ExplicitSave,
            "style",
        )
        .with_confidence(0.95)
        .with_stability(0.90);
        assert!(meta.base_staleness() < 0.3);
    }

    #[test]
    fn test_staleness_archived_high() {
        let meta = MemoryMeta::new(
            MemoryType::DeprecatedNote,
            MemorySource::AutoExtracted,
            "old",
        )
        .with_confidence(0.3)
        .with_stability(0.2)
        .with_status(MemoryStatus::Archived);
        assert!(meta.base_staleness() > 0.5);
    }

    #[test]
    fn stage4_p1_memory_meta_has_recall_weight_and_recall_count() {
        // ExplicitSave source defaults to recall_weight 0.8; AutoExtracted to 0.4.
        let m = MemoryMeta::new(
            MemoryType::UserPreference,
            MemorySource::ExplicitSave,
            "test",
        );
        assert_eq!(m.recall_weight, 0.8);
        assert_eq!(m.recall_count, 0);
        assert_eq!(m.last_recalled_at, None);
    }

    #[test]
    fn stage4_p1_with_recall_weight_clamps_to_unit_range() {
        let m = MemoryMeta::new(MemoryType::ProjectFact, MemorySource::AutoExtracted, "t")
            .with_recall_weight(1.5);
        assert_eq!(m.recall_weight, 1.0);
        let m2 = MemoryMeta::new(MemoryType::ProjectFact, MemorySource::AutoExtracted, "t")
            .with_recall_weight(-0.3);
        assert_eq!(m2.recall_weight, 0.0);
    }
}
